// Generated by CoffeeScript 1.9.3
(function() {
  casper.start('http://translate.google.com/', function() {
    this.sendKeys('#source', 'Guten Tag');
    this.then(function() {
      return this.click('#gt-submit');
    });
    this.waitForText('Good day');
    this.then(function() {
      return this.test.assertSelectorHasText('#result_box', 'Good day');
    });
    return this.then(function() {
      return this.capture('output.png');
    });
  });

  casper.run(function() {
    return this.test.done(1);
  });

}).call(this);
