// Generated by CoffeeScript 1.9.3
(function() {
  var filename;

  casper.start('http://www.google.com/', function() {
    return this.then(function() {
      this.echo('Foobar');
      return this.test.assertTitle('Google', 'google has the correct title');
    });
  });

  filename = '/home/velocita/ss_test_snapshots/Wed Nov 16 2016 1-14_test_results.txt';

  casper.run(function() {
    return this.exit();
  });

}).call(this);
