// Generated by CoffeeScript 1.9.3
(function() {
  casper.start('http://www.google.com/', function() {
    return this.then(function() {
      this.echo('Foobar');
      return this.test.assertTitle('Google', 'google has the correct title');
    });
  });

  casper.run(function() {
    return this.exit();
  });

}).call(this);
